
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package at.ac.tuwien.sepm.groupphase.backend.service.impl.logic;

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int AND = 3;
    public static final int AL = 10;
    public static final int SMALLER = 8;
    public static final int LITERAL = 13;
    public static final int NUMBER = 14;
    public static final int GREATER = 7;
    public static final int VARIABLE = 15;
    public static final int EOF = 0;
    public static final int BR = 6;
    public static final int COMMA = 12;
    public static final int error = 1;
    public static final int BL = 5;
    public static final int AR = 11;
    public static final int NOT = 2;
    public static final int EQUALS = 9;
    public static final int OR = 4;
    public static final String[] terminalNames = new String[] {
        "EOF",
        "error",
        "NOT",
        "AND",
        "OR",
        "BL",
        "BR",
        "GREATER",
        "SMALLER",
        "EQUALS",
        "AL",
        "AR",
        "COMMA",
        "LITERAL",
        "NUMBER",
        "VARIABLE"
    };
}

